"""
Render the shared glossary (glossary.yaml) into the site's Glossary page,
site/glossary.qmd (2026-09-27), grouped by domain, with the data
dictionaries that use each term.

  python export_glossary.py

tests/test_glossary.py checks that every dictionary's glossary matches this
one word for word, and that the page is current.
"""
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
OUT = (ROOT / "site" if (ROOT / "site").is_dir() else ROOT) / "glossary.qmd"  # vault layout, or the repo's
DOMAINS = {"music": "Music", "water and climate": "Water and climate", "data": "Data",
           "sources": "Sources", "making": "How the pieces are made"}


def load():
    return yaml.safe_load((ROOT / "glossary.yaml").read_text())


def dictionaries():
    """{dictionary name: {term: definition}} for every data dictionary in the project."""
    out = {}
    for p in sorted(ROOT.glob("data/**/*data-dict.yaml")) + sorted(ROOT.glob("tracks/mapping/*/data-dict.yaml")):
        d = yaml.safe_load(p.read_text())
        out[d["name"]] = {k: " ".join(str(v).split()) for k, v in (d.get("glossary") or {}).items()}
    return out


def render():
    terms, used = load(), dictionaries()
    L = ["---", 'title: "Glossary"', 'subtitle: "The words this project uses, from music, water and climate, and data"',
         "toc: true", "---", "",
         "<!-- generated by scripts/export_glossary.py from glossary.yaml; edit that, not this -->", "",
         "This is an interdisciplinary project, so its words come from several fields. Each term has one meaning "
         "everywhere: the [data dictionaries](methods.qmd#data-dictionaries) use these definitions word for word, "
         "and a test checks that they do. Where a term appears in a dictionary, the dictionary is named.", ""]
    for key, heading in DOMAINS.items():
        L += [f"## {heading}", ""]
        for t in sorted((t for t in terms if t["domain"] == key), key=lambda t: t["term"].lower()):
            L += [f"**{t['term']}**", f": {t['definition']}"]
            where = [n for n, g in used.items() if t["term"] in g]
            if where:
                L[-1] += f" *(in: {', '.join(where)})*"
            L.append("")
    return "\n".join(L) + "\n", len(terms)


def main():
    text, n = render()
    OUT.write_text(text)
    print(f"{OUT.relative_to(ROOT)}: {n} terms")


if __name__ == "__main__":
    sys.exit(main())
